from setuptools import setup,find_packages

setup(name='listcalendar',
        version='0.1',
        description='List google calendar incoming events',
        packages=find_packages(include=["listcalendar"]),
        url='http://github.com/milosoria/listcalendar',
        author='Camilo Soria',
        author_email='camilo.soria@uc.cl',
        license='MIT',
        package_data={'': ['*.json']},
        install_requires=[
            'cachetools==4.2.2',
            'certifi==2021.5.30',
            'charset-normalizer==2.0.4',
            'google-api-core==1.31.1',
            'google-api-python-client==2.33.0',
            'google-auth==1.34.0',
            'google-auth-httplib2==0.1.0',
            'google-auth-oauthlib==0.4.6',
            'googleapis-common-protos==1.53.0',
            'httplib2==0.19.1',
            'idna==3.2',
            'oauthlib==3.1.1',
            'packaging==21.0',
            'protobuf==3.17.3',
            'pyasn1==0.4.8',
            'pyasn1-modules==0.2.8',
            'pyparsing==2.4.7',
            'python-dateutil==2.8.2',
            'pytz==2021.1',
            'requests==2.26.0',
            'requests-oauthlib==1.3.0',
            'rsa==4.7.2',
            'six==1.16.0',
            'uritemplate==3.0.1',
            'urllib3==1.26.6'
            ],
        entry_points = {
            'console_scripts': ['listcalendar=listcalendar.__main__:main'],
            },
        zip_safe=False
        )
